
export default {

	CURRENT_LOCATION_CHANGED: 	'CURRENT_LOCATION_CHANGED',
	PLACES_RECEIVED: 			'PLACES_RECEIVED',
	POSTS_RECEIVED: 			'POSTS_RECEIVED',
	
	USERS_RECEIVED: 			'USERS_RECEIVED',
	USER_CREATED: 				'USER_CREATED',
	USER_LOGGED_IN: 			'USER_LOGGED_IN',
	USER_LOGGED_OUT: 			'USER_LOGGED_OUT',
	CURRENT_USER_RECEIVED: 		'CURRENT_USER_RECEIVED'

}